data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.0029602625534557803
  epochs: 233
  momentum: 0.7862974298311077
  weight_decay: 6.746822718505384e-05
  label_smoothing: 0.2258829204257719
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 56

seed:
  seednum: 2964

