data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 3.30656212790137
  epochs: 126
  momentum: 0.5323514308218449
  weight_decay: 1.283687425547748e-06
  label_smoothing: 0.0013835741033194626
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 91

seed:
  seednum: 30242

